In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
inventory= pd.read_csv('Inflight Service_Inventory data2.csv')
preorder= pd.read_csv('Inflight Service_Pre order data2.csv')
customer= pd.read_csv('Survey data _Customer comments2.csv')
satisfaction= pd.read_csv('Survey data_Inflight Satisfaction Score2.csv')

In [8]:
satisfaction.columns

Index(['flight_number', 'origin_station_code', 'destination_station_code',
       'record_locator', 'scheduled_departure_date', 'question_text', 'score',
       'satisfaction_type', 'driver_sub_group1', 'driver_sub_group2',
       'arrival_delay_minutes', 'arrival_delay_group', 'cabin_code_desc',
       'cabin_name', 'entity', 'number_of_legs', 'seat_factor_band',
       'loyalty_program_level', 'generation', 'fleet_type_description',
       'fleet_usage', 'equipment_type_code', 'ua_uax', 'actual_flown_miles',
       'haul_type', 'departure_gate', 'arrival_gate',
       'international_domestic_indicator', 'response_group', 'media_provider',
       'hub_spoke'],
      dtype='object')

In [9]:
inventory.rename(columns = {'departure_station_code':'origin_station_code', 'arrival_station_code':'destination_station_code', 'scheduled_departure_dtl':'scheduled_departure_date'}, inplace = True)
inventory.columns

Index(['flight_number', 'origin_station_code', 'destination_station_code',
       'scheduled_departure_date', 'entree_product_id', 'entree_description',
       'entree_code', 'planned_entree_count', 'consumed_entree_count'],
      dtype='object')

In [10]:
preorder.rename(columns = {'departure_station_code':'origin_station_code', 'arrival_station_code':'destination_station_code', 'scheduled_departure_dtl':'scheduled_departure_date'}, inplace = True)
preorder.columns

Index(['flight_number', 'origin_station_code', 'destination_station_code',
       'record_locator', 'carrier_code', 'scheduled_departure_date',
       'cabin_code', 'meal_group', 'meal_category', 'meal_short_description',
       'meal_description', 'is_entree', 'pre_order_qty'],
      dtype='object')

In [11]:
df_merge= pd.merge(satisfaction, inventory, on = ['flight_number', 'origin_station_code', 'destination_station_code'])
df_merge

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date_x,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,...,international_domestic_indicator,response_group,media_provider,hub_spoke,scheduled_departure_date_y,entree_product_id,entree_description,entree_code,planned_entree_count,consumed_entree_count
0,2231,ORX,DFX,I9XXHS,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,PANASONIC,hub departure,9/3/2022,61360,Brioche cheeseburger,B,3,0
1,2231,ORX,DFX,I9XXHS,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,PANASONIC,hub departure,9/10/2022,60983,Zatar chicken,C,8,0
2,2231,ORX,DFX,I9XXHS,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,PANASONIC,hub departure,9/5/2022,61360,Brioche cheeseburger,B,2,0
3,2231,ORX,DFX,I9XXHS,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,PANASONIC,hub departure,9/28/2022,60983,Zatar chicken,C,8,6
4,2231,ORX,DFX,I9XXHS,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,PANASONIC,hub departure,9/14/2022,60983,Zatar chicken,C,18,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817743,261,EWX,SFX,LVXXVM,9/30/2022,What item did you choose?,chicken entrée,NaN,food & beverage,comp,...,Domestic,member,PANASONIC,hub departure,9/30/2022,58065,Cacio e Pepe ravioli,P,7,0
817744,1450,SFX,BOX,PGXXMN,9/30/2022,How satisfied were you with the food & beverag...,4,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,THALES,hub departure,9/30/2022,61360,Brioche cheeseburger,B,2,0
817745,1450,SFX,BOX,PGXXMN,9/30/2022,How satisfied were you with the food & beverag...,4,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,THALES,hub departure,9/30/2022,60983,Zatar chicken,C,20,10
817746,1450,SFX,BOX,PGXXMN,9/30/2022,How satisfied were you with the food & beverag...,4,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,THALES,hub departure,9/30/2022,15594,Vegetarian entree,VG,2,2
817747,1450,SFX,BOX,PGXXMN,9/30/2022,How satisfied were you with the food & beverag...,4,Satisfied,food & beverage,food and beverage satisfaction,...,Domestic,member,THALES,hub departure,9/30/2022,60987,Impossible Meatball Bowl,V,16,6

In [12]:
df_merge= pd.merge(df_merge,preorder, on = ['flight_number', 'origin_station_code', 'destination_station_code', 'record_locator'])
df_merge

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date_x,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,...,consumed_entree_count,carrier_code,scheduled_departure_date,cabin_code,meal_group,meal_category,meal_short_description,meal_description,is_entree,pre_order_qty
0,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,10,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
1,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,0,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
2,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,0,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
3,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,0,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
4,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,8,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240350,402,SMX,ORX,PGXX2B,9/30/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,1,UA,9/30/2022,J,ENTREES HOT,POULTRY,Za’atar chicken,NaN,Y,3
240351,402,SMX,ORX,PGXX2B,9/30/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,10,UA,9/30/2022,J,ENTREES HOT,POULTRY,Za’atar chicken,NaN,Y,3
240352,1987,SFX,DCX,EZXXF0,9/30/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/30/2022,J,ENTREES HOT,BREAKFAST,Tomato and kale baked egg,Tomato and kale baked egg with fire roasted re...,Y,3
240353,1987,SFX,DCX,EZXXF0,9/30/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/30/2022,J,ENTREES HOT,BREAKFAST,Tomato and kale baked egg,Tomato and kale baked egg with fire roasted re...,Y,3
240354,1987,SFX,DCX,EZXXF0,9/30/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/30/2022,J,ENTREES HOT,BREAKFAST,Tomato and kale baked egg,Tomato and kale baked egg with fire roasted re...,Y,3

In [13]:
df_merge.dtypes
df_merge

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date_x,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,...,consumed_entree_count,carrier_code,scheduled_departure_date,cabin_code,meal_group,meal_category,meal_short_description,meal_description,is_entree,pre_order_qty
0,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,10,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
1,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,0,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
2,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,0,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
3,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,0,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
4,2416,RNX,DEX,AGXX6X,9/2/2022,What item did you choose?,other (specify),NaN,food & beverage,comp,...,8,UA,9/2/2022,J,NaN,NaN,I will decide onboard,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240350,402,SMX,ORX,PGXX2B,9/30/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,1,UA,9/30/2022,J,ENTREES HOT,POULTRY,Za’atar chicken,NaN,Y,3
240351,402,SMX,ORX,PGXX2B,9/30/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,10,UA,9/30/2022,J,ENTREES HOT,POULTRY,Za’atar chicken,NaN,Y,3
240352,1987,SFX,DCX,EZXXF0,9/30/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/30/2022,J,ENTREES HOT,BREAKFAST,Tomato and kale baked egg,Tomato and kale baked egg with fire roasted re...,Y,3
240353,1987,SFX,DCX,EZXXF0,9/30/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/30/2022,J,ENTREES HOT,BREAKFAST,Tomato and kale baked egg,Tomato and kale baked egg with fire roasted re...,Y,3
240354,1987,SFX,DCX,EZXXF0,9/30/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/30/2022,J,ENTREES HOT,BREAKFAST,Tomato and kale baked egg,Tomato and kale baked egg with fire roasted re...,Y,3

In [14]:
df_merge.dtypes

flight_number                        int64
origin_station_code                 object
destination_station_code            object
record_locator                      object
scheduled_departure_date_x          object
question_text                       object
score                               object
satisfaction_type                   object
driver_sub_group1                   object
driver_sub_group2                   object
arrival_delay_minutes                int64
arrival_delay_group                 object
cabin_code_desc                     object
cabin_name                          object
entity                              object
number_of_legs                       int64
seat_factor_band                    object
loyalty_program_level               object
generation                          object
fleet_type_description              object
fleet_usage                         object
equipment_type_code                 object
ua_uax                              object
actual_flown_miles                   int64
haul_type                           object
departure_gate                      object
arrival_gate                        object
international_domestic_indicator    object
response_group                      object
media_provider                      object
hub_spoke                           object
scheduled_departure_date_y          object
entree_product_id                    int64
entree_description                  object
entree_code                         object
planned_entree_count                 int64
consumed_entree_count                int64
carrier_code                        object
scheduled_departure_date            object
cabin_code                          object
meal_group                          object
meal_category                       object
meal_short_description              object
meal_description                    object
is_entree                           object
pre_order_qty                        int64
dtype: object

In [15]:
df_merge.shape

(240355, 46)

In [16]:
df_merge= df_merge.dropna()

In [17]:
df_merge['score'] = df_merge['score'].astype('int')

C:\Users\kesha\AppData\Local\Temp\ipykernel_4336\3517094240.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge['score'] = df_merge['score'].astype('int')

In [18]:
df_merge

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date_x,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,...,consumed_entree_count,carrier_code,scheduled_departure_date,cabin_code,meal_group,meal_category,meal_short_description,meal_description,is_entree,pre_order_qty
168,2399,TPX,IAX,BFXXFX,9/7/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,2,UA,9/7/2022,Y,LIQUOR,LIQUOR,Wheatley Vodka,TAX-PAID,N,1
169,2399,TPX,IAX,BFXXFX,9/7/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,2,UA,9/7/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1
170,2399,TPX,IAX,BFXXFX,9/7/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/7/2022,Y,LIQUOR,LIQUOR,Wheatley Vodka,TAX-PAID,N,1
171,2399,TPX,IAX,BFXXFX,9/7/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/7/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1
172,2399,TPX,IAX,BFXXFX,9/7/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/7/2022,Y,LIQUOR,LIQUOR,Wheatley Vodka,TAX-PAID,N,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240273,717,BUX,DEX,NQXX3P,9/27/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,11,UA,9/27/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1
240274,717,BUX,DEX,NQXX3P,9/27/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,9,UA,9/27/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1
240275,717,BUX,DEX,NQXX3P,9/27/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/27/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1
240276,717,BUX,DEX,NQXX3P,9/27/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,0,UA,9/27/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1
240277,717,BUX,DEX,NQXX3P,9/27/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,7,UA,9/27/2022,Y,UNITED CATERER OWNED 88-3F,SNACKS,Takeoff,Takeoff,N,1

In [19]:
df_merge['score'].unique()

array([1, 3, 5, 4, 2])

In [20]:
### Graph

In [21]:
df= df_merge[['origin_station_code','score']]
df_scores = df.groupby('origin_station_code').mean().reset_index()

In [22]:
df_counts = df.groupby('origin_station_code').count().reset_index().sort_values('score', ascending=False).iloc[:35]
df_counts = df_counts.reset_index().drop(columns = ['index']).rename(columns = {'score': 'count'})
df_counts

   origin_station_code  count
0                  DEX   2864
1                  IAX   2474
2                  SFX   1926
3                  ORX   1633
4                  EWX   1138
5                  LAX    574
6                  BOX    363
7                  TPX    273
8                  MCX    198
9                  FLX    132
10                 SAX    107
11                 PDX     98
12                 HNX     91
13                 LGX     88
14                 PHX     68
15                 ANX     62
16                 CLX     54
17                 BWX     51
18                 SNX     50
19                 OGX     48
20                 PIX     36
21                 SEX     35
22                 MEX     34
23                 MIX     34
24                 YYX     32
25                 BNX     28
26                 DCX     26
27                 PBX     24
28                 MBX     22
29                 LIX     21
30                 AUX     18
31                 RSX     18
32                 PUX     12
33                 SRX      6
34                 BUX      5

In [23]:
df_temp = df_scores.merge(df_counts).sort_values('count', ascending=False)
df_temp

   origin_station_code     score  count
8                  DEX  2.781774   2864
12                 IAX  2.950283   2474
30                 SFX  2.904465   1926
21                 ORX  3.199020   1633
9                  EWX  3.136204   1138
13                 LAX  4.181185    574
3                  BOX  3.079890    363
33                 TPX  1.805861    273
17                 MCX  2.050505    198
10                 FLX  4.454545    132
28                 SAX  3.168224    107
23                 PDX  1.979592     98
11                 HNX  2.527473     91
14                 LGX  3.522727     88
24                 PHX  3.264706     68
0                  ANX  3.000000     62
6                  CLX  2.666667     54
5                  BWX  3.549020     51
31                 SNX  4.000000     50
20                 OGX  1.166667     48
25                 PIX  1.000000     36
29                 SEX  1.142857     35
18                 MEX  4.000000     34
19                 MIX  1.000000     34
34                 YYX  4.000000     32
2                  BNX  5.000000     28
7                  DCX  2.000000     26
22                 PBX  3.000000     24
16                 MBX  1.000000     22
15                 LIX  2.333333     21
1                  AUX  1.000000     18
27                 RSX  2.000000     18
26                 PUX  5.000000     12
32                 SRX  5.000000      6
4                  BUX  2.000000      5